name: Deploy to Azure Storage

on:
  push:
    branches:
      - main  # Change to your branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/cli@v1
      with:
        inlineScript: |
          # Sync files to Azure Blob Storage
          az storage blob sync --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} --container devops321/mywebpage --source ./ --delete-detected --recursive
      env:
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
